# Generated by Django 5.1.1 on 2024-10-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loxury', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loxury',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='loxury',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loxury',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
