# Generated by Django 5.1.1 on 2024-10-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_gender_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/default-image.jpg', null=True, upload_to='avatars/'),
        ),
    ]
