# Generated by Django 5.1.1 on 2024-10-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_subemail_sub_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subemail',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='subemail',
            name='sub_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
